### ISSUE TITLE
Retire /t and /enyo

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-webui#51]
Since they're not used anymore - may be move them to the 'extras' instead of this?

**Comment by radare** [comment]
Wat. Both webuis are maintained, used and working. Extras have nothing to do with the web. So nope

**Comment by XVilka** [comment]
Why not focus on less? GUI is valued for the quality, not the quantity.

**Comment by radare** [comment]
Following this reasoning we should remove all archs from r2 except x86 and arm. Nobody is gonna focus on enyo or t, but they are simple, easy and clean implementations and are easy to modify and play with them. Theres no real reason to remove them. They are mot even compiled or installed unless the user wants them. And both make sense to exist:

/t is a tiled layout. The layouting is similar to dwm and can be easily hacked to support more layouts and panels are easy to do. In served as a discussion point with other ppl to evaluate new ways to show the info in /m

/enyo framework is great. Runs faster and in more browsers than /p or /m and the framework library is beautiful. Also, coding for it is structured and easy. In fact i took many ideas from this to do the /m in one night.

Again. We will only focus on /m, i though that was already clear since 0.10.2. But that doesnt means that i will remove those or block pullreqs from ppl pushing changes on those other webuis.
